### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by msjuck** [jackHedaya/pure-realtime-stock#1]
Hi, I have problem with the installation 

Here is log ....

[05:39:27 ubuntu@server STOCK]
[05:39:27 ubuntu@server STOCK]
[05:39:27 ubuntu@server STOCK]npm install pure-realtime-stock

> puppeteer@1.15.0 install /home/ubuntu/NODE/node_modules/puppeteer
> node install.js

Downloading Chromium r650583 - 110.5 Mb [====================] 100% 0.0s
Chromium downloaded to /home/ubuntu/NODE/node_modules/puppeteer/.local-chromium/linux-650583
npm WARN saveError ENOENT: no such file or directory, open '/home/ubuntu/NODE/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/ubuntu/NODE/package.json'
npm WARN NODE No description
npm WARN NODE No repository field.
npm WARN NODE No README data
npm WARN NODE No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ pure-realtime-stock@1.0.4
added 22 packages from 17 contributors in 16.234s

   ╭───────────────────────────────────────────────────────────────╮
   │                                                               │
   │       New minor version of npm available! 6.4.1 → 6.9.0       │
   │   Changelog: https://github.com/npm/cli/releases/tag/v6.9.0   │
   │               Run npm install -g npm to update!               │
   │                                                               │
   ╰───────────────────────────────────────────────────────────────╯

[05:39:46 ubuntu@server STOCK]npm install -g npm
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/agent-base
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/aproba
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/bluebird
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/builtin-modules
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/cidr-regex
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/colors
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/cli-table3
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/es6-promise
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/figgy-pudding
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/genfun
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/get-stream
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/glob
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/graceful-fs
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/is-builtin-module
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/JSONStream
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/libnpmhook/node_modules/npm-registry-fetch
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/lru-cache
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/minizlib
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/npm-bundled
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/npm-packlist
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/retry
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/ssri
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/npm-registry-client
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/npm-registry-fetch/node_modules/figgy-pudding
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/npm-registry-fetch/node_modules/pump
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/npm-registry-fetch/node_modules/cacache/node_modules/mississippi
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/npm-registry-fetch/node_modules/smart-buffer
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/npm-registry-fetch/node_modules/socks
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/npm-registry-fetch/node_modules/socks-proxy-agent
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/npm-registry-fetch/node_modules/ssri
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/npm-registry-fetch/node_modules/cacache
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/npm-registry-fetch/node_modules/make-fetch-happen
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/npm-registry-fetch
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/libnpmhook
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/npm-profile
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/protoduck
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/rimraf
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/semver
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/lock-verify
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/normalize-package-data
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/npm-pick-manifest
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/spdx-license-ids
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/ssri
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/cacache
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/string_decoder
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/tar/node_modules/yallist
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/tar
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/unique-filename
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/pacote
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/write-file-atomic
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/byte-size
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/chownr
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/ci-info
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/config-chain
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/is-cidr
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/libcipm
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/npm-audit-report
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/opener
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/query-string
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/read-package-tree
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/readable-stream
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/copy-concurrently/node_modules
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/fs-write-stream-atomic/node_modules
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/gauge/node_modules
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/gentle-fs/node_modules
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/libnpmhook/node_modules
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/npm-registry-client/node_modules
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/npm-registry-fetch/node_modulesnpm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/npm-registry-fetch/node_modules/cacache/node_modules
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/tar/node_modules
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/are-we-there-yet
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/concat-stream
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/duplexify
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/execa
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/flush-write-stream
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/from2
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/got
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/is-ci
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/move-concurrently
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/parallel-transform
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/run-queue
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/sha
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/stream-iterate
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/through2
npm ERR! path /usr/lib/node_modules/npm/node_modules/agent-base
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules/npm/node_modules/agent-base'
npm ERR!  { [Error: EACCES: permission denied, access '/usr/lib/node_modules/npm/node_modules/agent-base']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, access \'/usr/lib/node_modules/npm/node_modules/agent-base\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/lib/node_modules/npm/node_modules/agent-base' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2019-05-03T17_40_11_438Z-debug.log
[05:40:11 ubuntu@server STOCK]
[05:40:44 ubuntu@server STOCK]
[05:40:44 ubuntu@server STOCK]
[05:40:44 ubuntu@server STOCK]ls
stock.py
[05:40:45 ubuntu@server STOCK]ls
stock.py
[05:41:39 ubuntu@server STOCK]node stock.py
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module './helpers'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/ubuntu/NODE/node_modules/pure-realtime-stock/index.js:4:41)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
[05:41:41 ubuntu@server STOCK]npm install
npm WARN saveError ENOENT: no such file or directory, open '/home/ubuntu/NODE/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/ubuntu/NODE/package.json'
npm WARN NODE No description
npm WARN NODE No repository field.
npm WARN NODE No README data
npm WARN NODE No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

up to date in 5.682s

   ╭───────────────────────────────────────────────────────────────╮
   │                                                               │
   │       New minor version of npm available! 6.4.1 → 6.9.0       │
   │   Changelog: https://github.com/npm/cli/releases/tag/v6.9.0   │
   │               Run npm install -g npm to update!               │
   │                                                               │
   ╰───────────────────────────────────────────────────────────────╯

[05:42:22 ubuntu@server STOCK]sudo -s
[05:42:26 root@server STOCK]npm install -g npm
/usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
/usr/bin/npx -> /usr/lib/node_modules/npm/bin/npx-cli.js
+ npm@6.9.0
added 54 packages from 9 contributors, removed 15 packages and updated 47 packages in 7.978s
[05:42:38 root@server STOCK]
[05:42:40 root@server STOCK]
[05:42:40 root@server STOCK]exit
exit
[05:42:41 ubuntu@server STOCK]npm install pure-realtime-stock
npm WARN saveError ENOENT: no such file or directory, open '/home/ubuntu/NODE/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/ubuntu/NODE/package.json'
npm WARN NODE No description
npm WARN NODE No repository field.
npm WARN NODE No README data
npm WARN NODE No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ pure-realtime-stock@1.0.4
updated 1 package and audited 4711 packages in 4.644s
found 167 vulnerabilities (33 low, 116 moderate, 18 high)
  run `npm audit fix` to fix them, or `npm audit` for details
[05:42:51 ubuntu@server STOCK]npm audit fix
npm ERR! code EAUDITNOPJSON
npm ERR! audit No package.json found: Cannot audit a project without a package.json

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2019-05-03T17_43_05_597Z-debug.log
[05:43:05 ubuntu@server STOCK]
[05:43:07 ubuntu@server STOCK]
[05:43:07 ubuntu@server STOCK]sudo -s
[05:43:31 root@server STOCK]npm install pure-realtime-stock
npm WARN saveError ENOENT: no such file or directory, open '/home/ubuntu/NODE/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/ubuntu/NODE/package.json'
npm WARN NODE No description
npm WARN NODE No repository field.
npm WARN NODE No README data
npm WARN NODE No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ pure-realtime-stock@1.0.4
updated 1 package and audited 4711 packages in 4.735s
found 167 vulnerabilities (33 low, 116 moderate, 18 high)
  run `npm audit fix` to fix them, or `npm audit` for details
[05:43:39 root@server STOCK]ll
File_Permissions Owner Group size(Kb) Mod_time Name
total 12
drwxrwxr-x  2 ubuntu ubuntu 4096 May  3 17:24 ./
drwxrwxr-x 26 ubuntu ubuntu 4096 May  3 17:42 ../
-rw-rw-r--  1 ubuntu ubuntu  220 May  3 17:41 stock.py
[05:44:02 root@server STOCK]

**Comment by jackHedaya** [comment]
Hey, thanks for reaching out! What Ubuntu and Node version are you using? I'm going to test it out using Docker and investigate.

**Comment by jackHedaya** [comment]
I investigated and fixed a couple of issues in pure-realtime-stock. 

To fix, update pure-realtime-stock to version ^1.0.5 and install the Puppeteer dependencies as described [over here](https://github.com/GoogleChrome/puppeteer/issues/3443#issuecomment-433096772).

Future pure-realtime-stock versions will hopefully have a CLI walkthrough to have the dependencies installed automatically.
